name: Integration continue
on: 
  push:
      branches: [develop]
  pull_request:
      branches: [develop]    
jobs:
  compilling-app:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2
    - name: Autoriser l'exécution du fichier mvnw
      run: chmod +x ./mvnw  # Accorde les permissions d'exécution au fichier mvnw
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Compilation avec Maven
      run: mvn clean compile

      
  Tests-unitaires:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2
    - name: Autoriser l'exécution du fichier mvnw
      run: chmod +x ./mvnw  # Accorde les permissions d'exécution au fichier mvnw
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Exécution des tests unitaires
      run: ./mvnw test
  
  test-integrations:      
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2
    - name: Autoriser l'exécution du fichier mvnw
      run: chmod +x ./mvnw  # Accorde les permissions d'exécution au fichier mvnw 
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Exécution des tests d'intégration
      run: ./mvnw clean verify
      
  build-artefact:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2
    - name: Autoriser l'exécution du fichier mvnw
      run: chmod +x ./mvnw  # Accorde les permissions d'exécution au fichier mvnw
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build de l'artefact Quarkus
      run: mvn clean package -Dquarkus.package.type=uber-jar

    - name: Déplace le package dans le répertoire cible
      run: mv target/quarkus-app/* target/

    - name: Affiche les fichiers générés
      run: ls target/
    
    


      
  
